flasksite/posts/forms.py
from datetime import datetime

from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, TextAreaField, SubmitField, MultipleFileField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    date = DateField('Date', format='%Y-%m-%d', default=datetime.today)
    content = TextAreaField('Content', validators=[DataRequired()])
    media_file = MultipleFileField('Upload Media',
                                   validators=[FileAllowed(['jpg', 'png', 'gif', 'mp4', 'mov', 'webm'])])
    submit = SubmitField('Post')

flasksite/posts/routes.py
import os

from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app
from flask_login import current_user, login_required

from flasksite import db
from flasksite.models import Post
from flasksite.posts.forms import PostForm
from flasksite.posts.utils import save_media

posts = Blueprint('posts', __name__)


@posts.route("/posts")
def all_posts():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date.desc()).paginate(page=page, per_page=5)
    return render_template('posts.html', posts=posts)


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        media_file = []
        for file in form.media_file.data:
            if file.filename:
                media_file.append(save_media(file))
        post = Post(title=form.title.data, date=form.date.data, content=form.content.data, media_file=media_file,
                    author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('posts.all_posts'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = PostForm()
    if form.validate_on_submit():
        try:
            for file in post.media_file:
                os.remove(os.path.join(current_app.root_path, 'static/post_media', file))
        except FileNotFoundError:
            pass

        media_file = []
        for file in form.media_file.data:
            if file.filename:
                media_file.append(save_media(file))

        post.title = form.title.data
        post.date = form.date.data
        post.content = form.content.data
        post.media_file = media_file
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.all_posts'))
    elif request.method == 'GET':
        form.title.data = post.title
        form.date.data = post.date
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.media_file:
        for file in post.media_file:
            try:
                os.remove(os.path.join(current_app.root_path, 'static/post_media', file))
            except FileNotFoundError:
                pass
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('posts.all_posts'))

flasksite/users/routes.py
import os

from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app
from flask_login import login_user, current_user, logout_user, login_required

from flasksite import db, bcrypt
from flasksite.models import User
from flasksite.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm, \
    RequestAccessForm
from flasksite.users.utils import save_picture, send_reset_email, send_request_email, send_register_email, \
    verify_register_token

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
@login_required
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(surname=form.surname.data, forename=form.forename.data, username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/request", methods=['GET', 'POST'])
def request_access():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestAccessForm()
    if form.validate_on_submit():
        username = form.username.data
        surname = form.surname.data
        forename = form.forename.data
        email = form.email.data
        send_request_email(username, forename, surname, email)
        flash(
            'An admin has been notified of your request',
            'info')
        return redirect(url_for('main.home'))
    return render_template('request_access.html', title='Request Access', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            if current_user.image_file != 'default.jpg':
                try:
                    os.remove(os.path.join(current_app.root_path, 'static/profile_pics', current_user.image_file))
                except FileNotFoundError:
                    pass
            current_user.image_file = picture_file
        current_user.forename = form.forename.data
        current_user.surname = form.surname.data
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.forename.data = current_user.forename
        form.surname.data = current_user.surname
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='account', image_file=image_file, form=form)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash(
            'An email has been sent with instructions to reset your password',
            'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Password has been reset!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route("/register/<token>", methods=['GET', 'POST'])
def register_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = verify_register_token(token)
    if not user:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.request_access'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(surname=form.surname.data, forename=form.forename.data, username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/register/admin", methods=['GET', 'POST'])
def register_admin():
    send_register_email()
    flash('An email has been sent', 'success')
    return redirect(url_for('users.login'))

flasksite/templates/access_email.html
<!doctype html>
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Simple Transactional Email</title>
    <style>
      /* -------------------------------------
          GLOBAL RESETS
      ------------------------------------- */

      /*All the styling goes here*/

      img {
        border: none;
        -ms-interpolation-mode: bicubic;
        max-width: 100%;
      }

      body {
        background-color: #f6f6f6;
        font-family: sans-serif;
        -webkit-font-smoothing: antialiased;
        font-size: 14px;
        line-height: 1.4;
        margin: 0;
        padding: 0;
        -ms-text-size-adjust: 100%;
        -webkit-text-size-adjust: 100%;
      }

      table {
        border-collapse: separate;
        mso-table-lspace: 0pt;
        mso-table-rspace: 0pt;
        width: 100%; }
        table td {
          font-family: sans-serif;
          font-size: 14px;
          vertical-align: top;
      }

      /* -------------------------------------
          BODY & CONTAINER
      ------------------------------------- */

      .body {
        background-color: #f6f6f6;
        width: 100%;
      }

      /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
      .container {
        display: block;
        margin: 0 auto !important;
        /* makes it centered */
        max-width: 580px;
        padding: 10px;
        width: 580px;
      }

      /* This should also be a block element, so that it will fill 100% of the .container */
      .content {
        box-sizing: border-box;
        display: block;
        margin: 0 auto;
        max-width: 580px;
        padding: 10px;
      }

      /* -------------------------------------
          HEADER, FOOTER, MAIN
      ------------------------------------- */
      .main {
        background: #ffffff;
        border-radius: 3px;
        width: 100%;
      }

      .wrapper {
        box-sizing: border-box;
        padding: 20px;
      }

      .content-block {
        padding-bottom: 10px;
        padding-top: 10px;
      }

      .footer {
        clear: both;
        margin-top: 10px;
        text-align: center;
        width: 100%;
      }
        .footer td,
        .footer p,
        .footer span,
        .footer a {
          color: #999999;
          font-size: 12px;
          text-align: center;
      }

      /* -------------------------------------
          TYPOGRAPHY
      ------------------------------------- */
      h1,
      h2,
      h3,
      h4 {
        color: #000000;
        font-family: sans-serif;
        font-weight: 400;
        line-height: 1.4;
        margin: 0;
        margin-bottom: 30px;
      }

      h1 {
        font-size: 35px;
        font-weight: 300;
        text-align: center;
        text-transform: capitalize;
      }

      p,
      ul,
      ol {
        font-family: sans-serif;
        font-size: 14px;
        font-weight: normal;
        margin: 0;
        margin-bottom: 15px;
      }
        p li,
        ul li,
        ol li {
          list-style-position: inside;
          margin-left: 5px;
      }

      a {
        color: #3498db;
        text-decoration: underline;
      }

      /* -------------------------------------
          BUTTONS
      ------------------------------------- */
      .btn {
        box-sizing: border-box;
        width: 100%; }
        .btn > tbody > tr > td {
          padding-bottom: 15px; }
        .btn table {
          width: auto;
      }
        .btn table td {
          background-color: #ffffff;
          border-radius: 5px;
          text-align: center;
      }
        .btn a {
          background-color: #ffffff;
          border: solid 1px #3498db;
          border-radius: 5px;
          box-sizing: border-box;
          color: #3498db;
          cursor: pointer;
          display: inline-block;
          font-size: 14px;
          font-weight: bold;
          margin: 0;
          padding: 12px 25px;
          text-decoration: none;
          text-transform: capitalize;
      }

      .btn-primary table td {
        background-color: #3498db;
      }

      .btn-primary a {
        background-color: #3498db;
        border-color: #3498db;
        color: #ffffff;
      }

      /* -------------------------------------
          OTHER STYLES THAT MIGHT BE USEFUL
      ------------------------------------- */
      .last {
        margin-bottom: 0;
      }

      .first {
        margin-top: 0;
      }

      .align-center {
        text-align: center;
      }

      .align-right {
        text-align: right;
      }

      .align-left {
        text-align: left;
      }

      .clear {
        clear: both;
      }

      .mt0 {
        margin-top: 0;
      }

      .mb0 {
        margin-bottom: 0;
      }

      .preheader {
        color: transparent;
        display: none;
        height: 0;
        max-height: 0;
        max-width: 0;
        opacity: 0;
        overflow: hidden;
        mso-hide: all;
        visibility: hidden;
        width: 0;
      }

      .powered-by a {
        text-decoration: none;
      }

      hr {
        border: 0;
        border-bottom: 1px solid #f6f6f6;
        margin: 20px 0;
      }

      /* -------------------------------------
          RESPONSIVE AND MOBILE FRIENDLY STYLES
      ------------------------------------- */
      @media only screen and (max-width: 620px) {
        table[class=body] h1 {
          font-size: 28px !important;
          margin-bottom: 10px !important;
        }
        table[class=body] p,
        table[class=body] ul,
        table[class=body] ol,
        table[class=body] td,
        table[class=body] span,
        table[class=body] a {
          font-size: 16px !important;
        }
        table[class=body] .wrapper,
        table[class=body] .article {
          padding: 10px !important;
        }
        table[class=body] .content {
          padding: 0 !important;
        }
        table[class=body] .container {
          padding: 0 !important;
          width: 100% !important;
        }
        table[class=body] .main {
          border-left-width: 0 !important;
          border-radius: 0 !important;
          border-right-width: 0 !important;
        }
        table[class=body] .btn table {
          width: 100% !important;
        }
        table[class=body] .btn a {
          width: 100% !important;
        }
        table[class=body] .img-responsive {
          height: auto !important;
          max-width: 100% !important;
          width: auto !important;
        }
      }

      /* -------------------------------------
          PRESERVE THESE STYLES IN THE HEAD
      ------------------------------------- */
      @media all {
        .ExternalClass {
          width: 100%;
        }
        .ExternalClass,
        .ExternalClass p,
        .ExternalClass span,
        .ExternalClass font,
        .ExternalClass td,
        .ExternalClass div {
          line-height: 100%;
        }
        .apple-link a {
          color: inherit !important;
          font-family: inherit !important;
          font-size: inherit !important;
          font-weight: inherit !important;
          line-height: inherit !important;
          text-decoration: none !important;
        }
        #MessageViewBody a {
          color: inherit;
          text-decoration: none;
          font-size: inherit;
          font-family: inherit;
          font-weight: inherit;
          line-height: inherit;
        }
        .btn-primary table td:hover {
          background-color: #34495e !important;
        }
        .btn-primary a:hover {
          background-color: #34495e !important;
          border-color: #34495e !important;
        }
      }







    </style>
</head>
<body class="">
<span class="preheader">KingFisher Access Request.</span>
<table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
    <tr>
        <td>&nbsp;</td>
        <td class="container">
            <div class="content">

                <!-- START CENTERED WHITE CONTAINER -->
                <table role="presentation" class="main">

                    <!-- START MAIN CONTENT AREA -->
                    <tr>
                        <td class="wrapper">
                            <h1 class="navbar-brand mr-4">King<font color="LightBlue"><b><em>Fisher</em></b></font></h1>
                            <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                                <tr>
                                    <td>
                                        <p>Hello,</p>
                                        <p>A user has requested access to the site.</p>
                                        <ul>
                                            <li><b>Username: </b> {{ username }}</li>
                                            <li><b>Forename: </b>{{ forename }}</li>
                                            <li><b>Surname: </b> {{ surname }}</li>
                                            <li><b>Email: </b> {{ email }}</li>
                                        </ul>
                                        <p>To approve this request, login and fill out the following form to register a
                                            new user</p>
                                        <table role="presentation" border="0" cellpadding="0" cellspacing="0"
                                               class="btn btn-primary">
                                            <tbody>
                                            <tr>
                                                <td align="left">
                                                    <table role="presentation" border="0" cellpadding="0"
                                                           cellspacing="0">
                                                        <tbody>
                                                        <tr>
                                                            <td>
                                                                <a href="{{ url_for('users.register', _external=True)}}"
                                                                   target="_blank">Register User</a></td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <p>Or follow this link</p>
                                        <p>{{ url_for('users.register', _external=True)}}</p><br>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <!-- END MAIN CONTENT AREA -->
                </table>
                <!-- END CENTERED WHITE CONTAINER -->


            </div>
        </td>
        <td>&nbsp;</td>
    </tr>
</table>
</body>
</html>

flasksite/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<!-- Website developed by Dominic Too 2020 -->

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"
          integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" rel="stylesheet">
    <link href="/static/main.css" rel="stylesheet" type="text/css">

    <!-- Favicon -->
    <link href="/static/favicon/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180">
    <link href="/static/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png">
    <link href="/static/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png">
    <link href="/static/favicon/site.webmanifest" rel="manifest">
    <link color="#333333" href="/static/favicon/safari-pinned-tab.svg" rel="mask-icon">
    <link href="/static/favicon/favicon.ico" rel="shortcut icon">
    <meta content="#add8e6" name="msapplication-TileColor">
    <meta content="/static/favicon/browserconfig.xml" name="msapplication-config">
    <meta content="#add8e6" name="theme-color">

    {% if title %}
    <title>KingFisher - {{ title }} </title>
    {% else %}
    <title>KingFisher</title>
    {% endif %}

    {% block top %}
    {% endblock %}


</head>

<body data-offset="50" data-spy="scroll" data-target=".navbar">

<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/#">King<font color="LightBlue"><b><em>Fisher</em></b></font></a>
            <button aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
                    data-target="#navbarToggle" data-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">

                    {% block navbar %}

                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="/#home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/#about">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/#contact">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/#find">Find Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/#news">News</a>
                        </li>
                    </ul>

                    {% endblock %}

                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('users.account')}}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout')}}">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('users.login')}}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

<main class="container" role="main">
    <div class="row">

        {% block content %}

        {% endblock %}
    </div>

</main>

{% block bottom %}
{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script async crossorigin="anonymous" defer nonce="T77QHkcz"
        src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v7.0"></script>
<script crossorigin="anonymous"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

<script src="/static/main.js"></script>


</body>


</html>

flasksite/templates/post.html
{% extends "layout.html" %}
{% block content %}

<main class="container" role="main">
    <div class="row">

        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}

            <article class="media content-section">
                <img class="rounded-circle article-img"
                     src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
                <div class="media-body">
                    <div class="article-metadata">
                        <a class="mr-2">{{ post.author.forename + ' ' + post.author.surname }}</a>
                        <small class="text-muted">{{ post.date.strftime('%Y-%m-%d') }}</small>

                        {% if current_user.is_authenticated %}
                        <div>
                            <a class="btn btn-secondary btn-sm mt-1 mb-1"
                               href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                            <button class="btn btn-danger btn-sm m-1" data-target="#deleteModal" data-toggle="modal"
                                    type="button">Delete
                            </button>
                        </div>
                        {% endif %}

                    </div>
                    <h2 class="article-title">{{ post.title }}</h2>
                    <p class="article-content">{{ post.content }}</p>
                    {% if post.media_file %}

                    {% for file in post.media_file %}

                    {% if ( (".jpg" in file) or (".png" in file) or (".gif" in file) ) %}
                    <img . class="modalImage" id="{{ file.rsplit( ".", 1 )[ 0 ] }}" data-toggle="modal"
                    data-target="#modal{{ file.rsplit( ".", 1 )[ 0 ] }}"
                    style="max-height:150px"
                    src={{ url_for('static',filename='post_media/' + file) }}>


                    {% else %}

                    <video controls style=' max-height:50vh; max-width: 100%; height:auto;'>
                        <source src={{ url_for('static', filename='post_media/' + file) }}>
                        Your browser does not support video playback
                    </video>

                    {% endif %}

                    <!-- Modal -->
                    <div . class="modal fade" id="modal{{ file.rsplit( ".", 1 )[ 0 ] }}"
                    tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" style="height:auto;width:auto;">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button aria-label="Close" class="close" data-dismiss="modal" type="button">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div align="center" class="modal-body">
                                <img class="img-fluid" src={{ url_for('static',filename='post_media/' + file) }}>
                            </div>
                            <div class="modal-footer">
                                <button class="btn btn-secondary" data-dismiss="modal" type="button">Close</button>
                            </div>
                        </div>
                    </div>
                </div>

                {% endfor %}

                {% endif %}
        </div>
        </article>
        <!-- Modal -->
        <div aria-hidden="true" aria-labelledby="deleteModalLabel" class="modal fade" id="deleteModal" role="dialog"
             tabindex="-1">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                        <button aria-label="Close" class="close" data-dismiss="modal" type="button">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" data-dismiss="modal" type="button">Close</button>
                        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                            <input class="btn btn-danger" type="submit" value="Delete">
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
    </div>
</main>
{% endblock content %}